//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_WEB2.Pages.AdminPage
{


    public partial class AdminPage
    {

        /// <summary>
        /// AdminPageControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BTL_WEB2.Pages.AdminPage.AdminPageControl AdminPageControl;
    }
}
